export const FETCH_IMAGE_CARD = "FETCH_IMAGE_CARD";
export const FETCH_IMAGE_CARDS = "FETCH_IMAGE_CARDS";
export const CREATE_IMAGE_CARD = "CREATE_IMAGE_CARD";
export const EDIT_IMAGE_CARD = "EDIT_IMAGE_CARD";
export const DELETE_IMAGE_CARD = "DELETE_IMAGE_CARD";
